### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by groldan** [geoserver/geoserver-cloud#17]
Make it ready to deploy on k8s. Probably replacing `config` and `discovery` by kubernetes native services

**Comment by MikkelHJuul** [comment]
Hi, I have some feedback to give:
I ran `kompose convert` on the current docker-compose file. all in all, my findings were:
`config` and `discovery` was missing services (so I had to manually create some) (but as you say, you wan't to replace them with something native)
All relevant servers with environment variable `RABBITMQ_PORT` failed, and the variable had to be set explicitly.
All the services had healthchecks, but the health checks terminated the pods, because startup time was larger than 30sec (kubernetes default 3 failsx10 sec wait). I added `initialDelaySeconds: 120`

I manually removed volumes (but they probably failed because of the cluster set-up)

I haven't done a `kubectl apply -f "$(ls *.yaml | paste -sd, -)" -n <namespace>` with my changes to check if that works (to be fair, I havn't written most changes to the files, only deployed them live)

**Comment by MikkelHJuul** [comment]
another note: I manually removed the gateway and simply mapped the services manually.

The gateway seems to be redirecting incorrectly: like https://my.geoserver.comany.com/web/https,https://my.geoserver.comany.com,my.geoserver.comany.com/the/correct/path

this is fixed without it (connecting directly to the web-ui service

**Comment by danduk82** [comment]
done with https://github.com/camptocamp/helm-geoserver-cloud
