### ISSUE TITLE
Geoserver synchronization issues throught PostgreSQL

### ISSUE THREAD

**Issue by Ah1To** [geoserver/geoserver-cloud#210]
[docker-compose.yml](https://github.com/geoserver/geoserver-cloud/files/8231396/docker-compose.3.yml.txt)
 It's my compose file, i try to use postgresql as backend, gs was connected to db.
I have 2 geoservers and 1 postgreSQL server. I need to synchronize data between  geoserves which are located on different machines.
All data have stored in postgres `resources` table as blob, but when i use other clean geoserver which dont have any files inside it pulls files from resources table exclude `shp` file and when i try to load data from web preview i have next error
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://localhost:9090/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.reflect.UndeclaredThrowableExceptionCould not acquire data access &apos;StoreC&apos;
</ServiceException></ServiceExceptionReport>
```
![image](https://user-images.githubusercontent.com/23377812/157872180-a3ac54e2-f702-4ef8-9dce-300d03a82d82.png)

 I load shp file like `/rest/workspaces/{workspace}/datastores/{storename}/file.shp`, and file was uploaded and add in postgres db in resources table like blob.

![image](https://user-images.githubusercontent.com/23377812/157872447-f94396f3-5aa4-4f56-a92e-786f0a6bdeda.png)

**Comment by groldan** [comment]
If you need to use the jdbcconfig backend I suggest you try the latest stable version from this [docker-compose.yml|http://geoserver.org/geoserver-cloud/deploy/docker-compose/stable/jdbcconfig/docker-compose.yml] file directly and go from there, since several fixes have been applied since RC14.

This is the shared data directory one otherwise: [docker-compose.yml|http://geoserver.org/geoserver-cloud/deploy/docker-compose/stable/shared_datadir/docker-compose.yml].
